"""Compute every reported quantity into data/derived/results.json.

Inputs: Le Floch's pinned files (ground truth) and the floors written by
`qg enumerate` (data/floor/order{n}.tsv.gz). No number in REPORT.md or
CONTROLS.md is produced anywhere else.
"""

from __future__ import annotations

import gzip
import json
import sys
from collections import Counter
from itertools import combinations
from pathlib import Path

import highspy
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lefloch  # noqa: E402

ROOT = lefloch.ROOT
N = lefloch.N_LAWS
ORDERS = list(range(1, 7))
FULL = (1 << N) - 1
DERIVED = ROOT / "data" / "derived"


def bits(laws) -> int:
    x = 0
    for i in laws:
        x |= 1 << (i - 1)
    return x


def popcount(x: int) -> int:
    return x.bit_count()


def read_floor(n: int):
    """Distinct signatures at order n: sig -> [iso class count, lex-least table]."""
    out: dict[frozenset[int], list] = {}
    with gzip.open(ROOT / "data" / "floor" / f"order{n}.tsv.gz", "rt") as f:
        header = next(f).rstrip("\n").split("\t")
        assert header == ["order", "table", "aut", "satisfied"], header
        for line in f:
            o, table, _aut, sat = line.rstrip("\n").split("\t")
            assert int(o) == n
            s = frozenset() if sat == "-" else frozenset(map(int, sat.split(",")))
            if s in out:
                out[s][0] += 1
            else:
                out[s] = [1, table]  # rows are sorted, so the first table is the least
    return out


def read_parastrophe():
    maps = {}
    for line in (DERIVED / "parastrophe.tsv").read_text().splitlines()[1:]:
        sigma, mapped, bij, m = line.split("\t")
        assert bij == "true"
        maps[sigma] = [int(x) for x in m.split(",")]
    return maps


def act(tau: list[int], s: frozenset[int]) -> frozenset[int]:
    """Signature of Q^sigma from that of Q: L holds in Q^sigma iff tau(L) holds in Q."""
    return frozenset(l for l in range(1, N + 1) if tau[l - 1] in s)


def pretty_table(table: str, n: int) -> list[str]:
    return [" ".join(table[r * n : (r + 1) * n]) for r in range(n)]


def smallest_long_class(gt, laws: frozenset[int]) -> frozenset[int]:
    cands = [c for c in gt.long_classes if laws <= c]
    out = frozenset(range(1, N + 1))
    for c in cands:
        out &= c
    return out


def variety_name(gt, c: frozenset[int]) -> str:
    """Smallest (then lexicographically least) set of representatives generating c."""
    reps = sorted({gt.rep_of[x] for x in c})
    if not reps:
        return "()"
    for size in range(1, len(reps) + 1):
        for combo in combinations(reps, size):
            if smallest_long_class(gt, frozenset(x for r in combo for x in gt.classes[r])) == c:
                return "(" + ", ".join(map(str, combo)) + ")"
    raise AssertionError("closed set not generated by its own laws")


def solve_cover(sets: list[set[int]], universe: list[int], weights=None, integer=True, fix_count=None):
    """min sum w_s x_s  s.t. every u is covered; HiGHS. Returns (objective, chosen indices, status)."""
    h = highspy.Highs()
    h.setOptionValue("output_flag", False)
    m = len(sets)
    w = np.array(weights if weights is not None else [1.0] * m, dtype=np.float64)
    h.addCols(m, w, np.zeros(m), np.ones(m), 0, np.array([], dtype=np.int32), np.array([], dtype=np.int32), np.array([]))
    if integer:
        h.changeColsIntegrality(m, np.arange(m, dtype=np.int32), np.array([highspy.HighsVarType.kInteger] * m))
    covering = {u: [] for u in universe}
    for si, s in enumerate(sets):
        for u in s:
            if u in covering:
                covering[u].append(si)
    for u in universe:
        idx = np.array(covering[u], dtype=np.int32)
        assert len(idx) > 0, "uncoverable element"
        h.addRow(1.0, highspy.kHighsInf, len(idx), idx, np.ones(len(idx)))
    if fix_count is not None:
        idx = np.arange(m, dtype=np.int32)
        h.addRow(fix_count, fix_count, m, idx, np.ones(m))
    h.run()
    status = h.modelStatusToString(h.getModelStatus())
    obj = h.getInfo().objective_function_value
    x = list(h.getSolution().col_value)
    chosen = [i for i, v in enumerate(x) if v > 0.5] if integer else None
    return obj, chosen, status, x


def main() -> None:
    gt = lefloch.load()
    reps = gt.reps
    long_set = set(gt.long_classes)
    long_index = {c: i + 1 for i, c in enumerate(gt.long_classes)}
    res: dict = {"lefloch_consistency": lefloch.consistency(gt)}

    # ---- floors -------------------------------------------------------------
    floors = {n: read_floor(n) for n in ORDERS}
    first_order: dict[frozenset[int], int] = {}
    table_of: dict[frozenset[int], str] = {}
    for n in ORDERS:
        for s, (cnt, table) in floors[n].items():
            if s not in first_order:
                first_order[s], table_of[s] = n, table

    # ---- ground truth masks -------------------------------------------------
    imp_row = {i: bits(gt.closure_of_rep[gt.rep_of[i]]) for i in range(1, N + 1)}
    rep_pos = {r: k for k, r in enumerate(reps)}
    RMASK = (1 << len(reps)) - 1
    rep_imp_row = {r: sum(1 << rep_pos[s] for s in gt.rep_implies[r]) for r in reps}
    n_imp_offdiag = sum(popcount(imp_row[i]) for i in range(1, N + 1)) - N
    n_pairs = N * (N - 1)
    n_nonimp = n_pairs - n_imp_offdiag
    n_class_pairs = len(reps) * (len(reps) - 1)
    n_class_imp = sum(popcount(rep_imp_row[r]) for r in reps) - len(reps)
    n_class_nonimp = n_class_pairs - n_class_imp
    res["pair_space"] = {
        "ordered_law_pairs_offdiagonal": n_pairs,
        "law_implications_offdiagonal": n_imp_offdiag,
        "law_non_implications": n_nonimp,
        "ordered_class_pairs_offdiagonal": n_class_pairs,
        "class_implications_offdiagonal": n_class_imp,
        "class_non_implications": n_class_nonimp,
    }

    # ---- cumulative sweep ---------------------------------------------------
    per_order = []
    refuted = {i: 0 for i in range(1, N + 1)}
    rep_refuted = {r: 0 for r in reps}
    cum_sigs: set[frozenset[int]] = set()
    closed: set[frozenset[int]] = {frozenset(range(1, N + 1))}
    satisfied_by_order_ge2 = 0
    prev_law_cov = prev_class_cov = prev_var = prev_sigs = 0
    for n in ORDERS:
        sigs_n = set(floors[n])
        new_sigs = sigs_n - cum_sigs
        cum_sigs |= sigs_n
        for s in new_sigs:
            comp = FULL & ~bits(s)
            for i in s:
                refuted[i] |= comp
            srep = {r for r in reps if r in s}
            rcomp = RMASK & ~sum(1 << rep_pos[r] for r in srep)
            for r in srep:
                rep_refuted[r] |= rcomp
        if n >= 2:
            for s in sigs_n:
                satisfied_by_order_ge2 |= bits(s)
        # G2 confusion matrices
        law_ref_imp = sum(popcount(refuted[i] & imp_row[i]) for i in range(1, N + 1))
        law_ref_non = sum(popcount(refuted[i] & ~imp_row[i] & FULL) for i in range(1, N + 1))
        class_ref_imp = sum(popcount(rep_refuted[r] & rep_imp_row[r]) for r in reps)
        class_ref_non = sum(popcount(rep_refuted[r] & ~rep_imp_row[r] & RMASK) for r in reps)
        # varieties: intersections of floor signatures (and the full set)
        frontier = set(closed) | set(new_sigs)
        closed |= set(new_sigs)
        while True:
            new = {a & b for a in closed for b in cum_sigs} - closed
            if not new:
                break
            closed |= new
        # law partition by signature columns
        sig_list = sorted(cum_sigs, key=lambda s: (len(s), sorted(s)))
        column = {i: tuple(k for k, s in enumerate(sig_list) if i in s) for i in range(1, N + 1)}
        blocks = Counter(column.values())
        classes_split = sum(1 for r in reps if len({column[x] for x in gt.classes[r]}) > 1)
        block_classes: dict[tuple, set[int]] = {}
        for r in reps:
            block_classes.setdefault(column[r], set()).add(r)
        merged = sorted(sorted(v) for v in block_classes.values() if len(v) > 1)
        trivial_only = [i for i in range(1, N + 1) if not (satisfied_by_order_ge2 >> (i - 1)) & 1] if n >= 2 else None
        row = {
            "order": n,
            "iso_classes_at_order": sum(c for c, _ in floors[n].values()),
            "distinct_signatures_at_order": len(sigs_n),
            "distinct_signatures_cumulative": len(cum_sigs),
            "new_signatures": len(new_sigs),
            "signatures_not_among_long_classes": len([s for s in cum_sigs if s not in long_set]),
            "law_refuted_but_implication": law_ref_imp,
            "law_refuted_non_implication": law_ref_non,
            "law_unrefuted_non_implication": n_nonimp - law_ref_non,
            "law_unrefuted_implication": n_imp_offdiag - law_ref_imp,
            "class_refuted_but_implication": class_ref_imp,
            "class_refuted_non_implication": class_ref_non,
            "class_unrefuted_non_implication": n_class_nonimp - class_ref_non,
            "class_unrefuted_implication": n_class_imp - class_ref_imp,
            "law_saturation": law_ref_non / n_nonimp,
            "class_saturation": class_ref_non / n_class_nonimp,
            "law_pairs_new": law_ref_non - prev_law_cov,
            "class_pairs_new": class_ref_non - prev_class_cov,
            "closed_sets": len(closed),
            "closed_sets_not_long_classes": len(closed - long_set),
            "varieties_realized": len(closed & long_set),
            "varieties_new": len(closed & long_set) - prev_var,
            "varieties_as_single_signature": len(cum_sigs & long_set),
            "law_blocks": len(blocks),
            # classes in a block of their own: separated from every other class
            "classes_separated": sum(1 for v in block_classes.values() if len(v) == 1),
            "classes_split_by_floor": classes_split,
            "merged_class_groups": merged,
            "trivial_only_laws": None if trivial_only is None else len(trivial_only),
            "trivial_only_vacuous_pairs": None if trivial_only is None else len(trivial_only) * (N - 1),
            "missing_varieties": sorted(variety_name(gt, c) for c in long_set - closed),
        }
        prev_law_cov, prev_class_cov, prev_var, prev_sigs = law_ref_non, class_ref_non, row["varieties_realized"], len(cum_sigs)
        per_order.append(row)
        del frontier
    res["per_order"] = per_order

    unrefuted_class_pairs = [
        [a, b] for a in reps for b in reps if a != b and not (rep_refuted[a] >> rep_pos[b]) & 1 and not (rep_imp_row[a] >> rep_pos[b]) & 1
    ]
    res["unrefuted_class_non_implications_at_order_6"] = unrefuted_class_pairs

    # ---- signatures table ---------------------------------------------------
    sig_rows = []
    for s in sorted(cum_sigs, key=lambda s: (first_order[s], len(s), sorted(s))):
        n0 = first_order[s]
        counts = {n: floors[n][s][0] if s in floors[n] else 0 for n in ORDERS}
        sig_rows.append(
            {
                "first_order": n0,
                "laws_satisfied": len(s),
                "long_class_index": long_index.get(s),
                "variety": variety_name(gt, s) if s in long_set else None,
                "iso_classes_by_order": counts,
                "least_table": table_of[s],
                "satisfied": sorted(s),
            }
        )
    res["signatures"] = sig_rows

    # ---- parastrophe action -------------------------------------------------
    maps = read_parastrophe()
    taus = list(maps.values())
    def orbit_key_law(l):
        return min(t[l - 1] for t in taus)
    law_orbits = len({frozenset(t[l - 1] for t in taus) for l in range(1, N + 1)})
    fixed = [sum(1 for l in range(1, N + 1) if t[l - 1] == l) for t in taus]
    pair_orbits = sum(f * (f - 1) for f in fixed) // len(taus)
    nonimp_fixed = [
        sum(1 for i in range(1, N + 1) if t[i - 1] == i for j in range(1, N + 1) if j != i and t[j - 1] == j and not gt.implies(i, j))
        for t in taus
    ]
    nonimp_orbits = sum(nonimp_fixed) // len(taus)
    class_images_ok = all(
        len({gt.rep_of[t[x - 1]] for x in gt.classes[r]}) == 1 for t in taus for r in reps
    )
    class_orbits = len({frozenset(gt.rep_of[t[r - 1]] for t in taus) for r in reps})
    rep_maps = [{r: gt.rep_of[t[r - 1]] for r in reps} for t in taus]
    class_pair_orbits = len({min((mp[a], mp[b]) for mp in rep_maps) for a in reps for b in reps if a != b})
    class_nonimp_orbits = len(
        {min((mp[a], mp[b]) for mp in rep_maps) for a in reps for b in reps if a != b and b not in gt.rep_implies[a]}
    )
    def act_set(t, c):
        return frozenset(l for l in range(1, N + 1) if t[l - 1] in c)
    variety_images_ok = all(act_set(t, c) in long_set for t in taus for c in long_set)
    variety_orbits = len({frozenset(act_set(t, c) for t in taus) for c in long_set})
    closure_per_order = {}
    canon_per_order = {}
    cum = set()
    for n in ORDERS:
        sn = set(floors[n])
        closure_per_order[str(n)] = all(act_set(t, s) in sn for t in taus for s in sn)
        cum |= sn
        canon_per_order[str(n)] = {
            "at_order": len({min(tuple(sorted(act_set(t, s))) for t in taus) for s in sn}),
            "cumulative": len({min(tuple(sorted(act_set(t, s))) for t in taus) for s in cum}),
        }
    res["parastrophe"] = {
        "group_order": len(taus),
        "all_maps_bijective": True,
        "fixed_laws_per_sigma": dict(zip(maps.keys(), fixed)),
        "law_orbits": law_orbits,
        "ordered_pair_orbits": pair_orbits,
        "non_implication_orbits": nonimp_orbits,
        "classes_map_to_classes": class_images_ok,
        "class_orbits": class_orbits,
        "class_pair_orbits": class_pair_orbits,
        "class_non_implication_orbits": class_nonimp_orbits,
        "varieties_map_to_varieties": variety_images_ok,
        "variety_orbits": variety_orbits,
        "signature_sets_closed_under_action": closure_per_order,
        "canonical_signatures": canon_per_order,
    }

    # ---- minimum cover ------------------------------------------------------
    universe = [rep_pos[a] * len(reps) + rep_pos[b] for a in reps for b in reps
                if a != b and (rep_refuted[a] >> rep_pos[b]) & 1]
    cand = sorted(cum_sigs, key=lambda s: (first_order[s], table_of[s]))
    cover_sets = []
    for s in cand:
        srep = [r for r in reps if r in s]
        out = [r for r in reps if r not in s]
        cover_sets.append({rep_pos[a] * len(reps) + rep_pos[b] for a in srep for b in out})
    # greedy: most new pairs, ties to smaller order then smaller table
    left, greedy = set(universe), []
    while left:
        best = max(range(len(cand)), key=lambda k: (len(cover_sets[k] & left), -first_order[cand[k]], [-ord(c) for c in table_of[cand[k]]]))
        greedy.append(best)
        left -= cover_sets[best]
    lp_obj, _, lp_status, _ = solve_cover(cover_sets, universe, integer=False)
    ilp_obj, ilp_chosen, ilp_status, _ = solve_cover(cover_sets, universe)
    opt = round(ilp_obj)
    ord_obj, ord_chosen, ord_status, _ = solve_cover(
        cover_sets, universe, weights=[float(first_order[s]) for s in cand], fix_count=opt
    )
    law_weight = {u: len(gt.classes[reps[u // len(reps)]]) * len(gt.classes[reps[u % len(reps)]]) for u in universe}

    def describe(idx):
        s = cand[idx]
        n0 = first_order[s]
        return {
            "order": n0,
            "table_rows": pretty_table(table_of[s], n0),
            "table": table_of[s],
            "laws_satisfied": len(s),
            "variety": variety_name(gt, s) if s in long_set else None,
            "class_pairs_covered": len(cover_sets[idx]),
            "law_pairs_covered": sum(law_weight[u] for u in cover_sets[idx]),
            "satisfied": sorted(s),
        }

    per_k_opt = {}
    for k in ORDERS:
        ks = [i for i, s in enumerate(cand) if first_order[s] <= k]
        uk = sorted(set().union(*(cover_sets[i] for i in ks))) if ks else []
        if uk:
            o, _, st, _ = solve_cover([cover_sets[i] for i in ks], uk)
            per_k_opt[k] = {"universe_class_pairs": len(uk), "optimal_cover_size": round(o), "status": st}
        else:
            per_k_opt[k] = {"universe_class_pairs": 0, "optimal_cover_size": 0, "status": "empty"}
    res["cover"] = {
        "universe": "class-level non-implications witnessed by the floor at order <= 6",
        "universe_class_pairs": len(universe),
        "universe_law_pairs": sum(law_weight.values()),
        "candidates_distinct_signatures": len(cand),
        "greedy_size": len(greedy),
        "greedy": [describe(i) for i in greedy],
        "lp_bound": lp_obj,
        "lp_status": lp_status,
        "ilp_optimum": opt,
        "ilp_status": ilp_status,
        "order_weighted_status": ord_status,
        "order_weighted_total_order": round(ord_obj),
        "optimal": [describe(i) for i in sorted(ord_chosen, key=lambda i: (first_order[cand[i]], table_of[cand[i]]))],
        "optimal_by_max_order": per_k_opt,
    }

    # ---- single tiny quasigroups (the magma paper's "degenerate" analogue) --
    tiny = []
    for i, s in enumerate(cand):
        if first_order[s] <= 3:
            tiny.append(describe(i) | {"law_share_of_non_implications": describe(i)["law_pairs_covered"] / n_nonimp})
    res["tiny_quasigroups"] = tiny

    DERIVED.mkdir(parents=True, exist_ok=True)
    (DERIVED / "results.json").write_text(json.dumps(res, indent=1, sort_keys=True, default=list) + "\n")

    # plain data exports
    sig_dir = ROOT / "data" / "signatures"
    sig_dir.mkdir(parents=True, exist_ok=True)
    with open(sig_dir / "distinct_signatures.tsv", "w") as f:
        f.write("first_order\tlaws_satisfied\tlong_class_index\tvariety\t" + "\t".join(f"iso_classes_order{n}" for n in ORDERS) + "\tleast_table\tsatisfied\n")
        for r in sig_rows:
            f.write(
                f"{r['first_order']}\t{r['laws_satisfied']}\t{r['long_class_index']}\t{r['variety']}\t"
                + "\t".join(str(r["iso_classes_by_order"][n]) for n in ORDERS)
                + f"\t{r['least_table']}\t{','.join(map(str, r['satisfied'])) or '-'}\n"
            )
    cover_dir = ROOT / "data" / "cover"
    cover_dir.mkdir(parents=True, exist_ok=True)
    with open(cover_dir / "min_cover.tsv", "w") as f:
        f.write("order\ttable\tlaws_satisfied\tvariety\tclass_pairs_covered\tlaw_pairs_covered\tsatisfied\n")
        for r in res["cover"]["optimal"]:
            f.write(f"{r['order']}\t{r['table']}\t{r['laws_satisfied']}\t{r['variety']}\t{r['class_pairs_covered']}\t{r['law_pairs_covered']}\t{','.join(map(str, r['satisfied'])) or '-'}\n")
    print(json.dumps({k: v for k, v in res.items() if k in ("pair_space",)}, indent=1))
    for row in per_order:
        print({k: row[k] for k in ("order", "distinct_signatures_cumulative", "law_refuted_but_implication", "signatures_not_among_long_classes", "law_saturation", "class_saturation", "varieties_realized", "law_blocks")})
    print("cover", len(universe), "greedy", len(greedy), "lp", lp_obj, "ilp", opt, ilp_status)


if __name__ == "__main__":
    main()
