"""Generate REPORT.md, CONTROLS.md and figures/saturation.png.

Every number in both documents is read from data/derived/* or the pinned
input files and formatted here. Nothing is typed by hand. Edit this script,
not the Markdown.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gates  # noqa: E402
import lefloch  # noqa: E402

ROOT = gates.ROOT
DER = gates.DERIVED
ORDERS = gates.ORDERS
GEN = "<!-- Generated by analysis/report.py from data/derived/. Do not edit by hand. -->"
CITE = (
    "Bruno Le Floch, *Implication semilattice of 990 quasigroup equational laws*, "
    "[arXiv:2603.29909v1](https://arxiv.org/abs/2603.29909) (31 March 2026), CC BY 4.0"
)


def pct(x: float) -> str:
    return f"{100 * x:.2f}%"


def num(x: int) -> str:
    return f"{x:,}"


def table(header: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def sch(group) -> str:
    return ", ".join(f"Sch-{r}" for r in group)


def machine() -> dict[str, str]:
    return dict(line.split("\t", 1) for line in (DER / "machine.tsv").read_text().splitlines())


def figure(res: dict) -> str:
    rows = res["per_order"]
    n_var = res["lefloch_consistency"]["n_long_classes"]
    xs = [r["order"] for r in rows]
    fig, ax = plt.subplots(figsize=(6.4, 4.0), dpi=150)
    ax.plot(xs, [100 * r["law_saturation"] for r in rows], marker="o", label="law-level non-implications witnessed")
    ax.plot(xs, [100 * r["class_saturation"] for r in rows], marker="s", label="class-level non-implications witnessed")
    ax.plot(xs, [100 * r["varieties_realized"] / n_var for r in rows], marker="^", label="varieties realised as floor-closed sets")
    ax.set_xlabel("maximum quasigroup order k")
    ax.set_ylabel("percent (cumulative, floor at order ≤ k)")
    ax.set_ylim(0, 100)
    ax.set_xticks(xs)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    path = ROOT / "figures" / "saturation.png"
    path.parent.mkdir(exist_ok=True)
    fig.savefig(path, metadata={"Software": None})
    plt.close(fig)
    return "figures/saturation.png"


def beyond_json() -> dict | None:
    p = DER / "beyond.json"
    return json.loads(p.read_text()) if p.exists() else None


def fingerprints() -> list[list[str]]:
    p = ROOT / "data" / "controls" / "oeis_fingerprints.tsv"
    return [line.split("\t") for line in p.read_text().splitlines()[1:]] if p.exists() else []


def beyond_section(res: dict, n_cls: int, n_var: int) -> list[str]:
    b = beyond_json()
    if not b:
        return []
    ps = res["pair_space"]
    top = b["complete_upto"]
    L = ["## 8. Beyond order 6, exactly", "",
         "Every separation still open at order 6 involves a variety not yet realised. Whether a class pair `a ↛ b` is "
         "witnessed at order ≤ k depends only on the models of `a`, and whether a variety V is realised at order ≤ k depends "
         "only on the models of V. So it is enough to enumerate, exhaustively and up to isomorphism, the models of the "
         f"{len(b['generators'])} varieties missing at order 6 (`qg models`, `src/search.rs`: row-major backtracking that "
         "cuts a branch as soon as a required law fails on defined entries, with the enumerator's symmetry breaking and "
         "canonicity test). The curves below are exact through the largest order at which every one of these runs "
         f"finished: **order {top}**.", ""]
    L += [table(["max order k", f"class non-implications witnessed (of {num(ps['class_non_implications'])})", "share",
                 "law share", f"blocks of classes (of {n_cls})", f"classes separated from all others (of {n_cls})",
                 f"varieties realised (of {n_var})"],
                [[r["order"], num(r["class_non_implications_witnessed"]), pct(r["class_saturation"]), pct(r["law_saturation"]),
                  r["class_blocks"], r["classes_separated"], r["varieties_realised"]] for r in b["curve"]]), ""]
    last = b["curve"][-1]
    L += [f"Varieties still not realised at order ≤ {top}: "
          + (", ".join(f"Sch-{v}" for v in last["missing_varieties"]) if last["missing_varieties"] else "none") + ".", ""]
    L += ["Least order at which each variety missing at order 6 is realised:", "",
          table(["variety", "least realising order"],
                [[f"Sch-{k}", v if v is not None else f"> {top}"] for k, v in sorted(b["least_variety_order"].items(),
                 key=lambda kv: (kv[1] is None, kv[1] or 0, kv[0]))]), ""]
    agree = sum(1 for p in b["least_pair_order"] if p["exhaustive_least_order"] == p["mace4_order"])
    L += [f"Least witness order for the {len(b['least_pair_order'])} residual class pairs, now exhaustive: it agrees with "
          f"Mace4 for {agree} of them.", ""]
    groups: dict[tuple, list[int]] = {}
    for p in b["least_pair_order"]:
        groups.setdefault((p["a"], p["exhaustive_least_order"]), []).append(p["b"])
    L += [f"- Sch-{a} ↛ " + ", ".join(f"Sch-{x}" for x in sorted(bs)) + f": order {o if o is not None else f'> {top}'}"
          for (a, o), bs in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1] or 0))]
    L += [""]
    c = b.get("full_cover")
    if c:
        optimal_any = c["optimum_known_signatures"] == c["lower_bound_any_quasigroups"]
        L += ["### Cover of every class non-implication", "",
              f"All {num(c['universe_class_pairs'])} class-level non-implications are witnessed at order ≤ {top}. "
              f"The smallest cover among the {c['candidates']} signatures found has **{c['optimum_known_signatures']}** "
              f"quasigroups ({c['status']}). Every signature of any quasigroup is closed under consequence, hence one of Le "
              f"Floch's {n_var} varieties if his list is complete; under that assumption the same ILP over all {n_var} "
              f"varieties bounds every possible cover from below: {c['lower_bound_any_quasigroups']} "
              f"({c['lower_bound_status']}). "
              + ("The bounds meet, so this cover is optimal among quasigroups of every order, given his list." if optimal_any
                 else "The bounds do not meet."), ""]
        prof: dict[int, int] = {}
        for m in c["members"]:
            prof[m["order"]] = prof.get(m["order"], 0) + 1
        L += ["Order profile (minimising total order among optimal covers): "
              + ", ".join(f"order {k}: {v}" for k, v in sorted(prof.items())) + ".", ""]
        big = [m for m in c["members"] if m["order"] > 6]
        for m in big:
            L += [f"Order {m['order']}, variety Sch-{m['variety']}, covers {m['class_pairs_covered']} class pairs:", "",
                  "```", *m["table_rows"], "```", ""]
        L += ["All member tables: `data/derived/beyond.json` (`full_cover`).", ""]

    L += ["## 9. Model counts by order", "",
          "Isomorphism classes of quasigroups satisfying each class representative, by order. Orders ≤ 6 come from the "
          f"floor; larger orders are filled only where an exhaustive run covers the class exactly. Counts for all "
          f"{n_var} varieties: `data/signatures/model_counts.tsv`.", ""]
    orders = [str(n) for n in range(1, top + 1)]
    L += [table(["class"] + [f"n={n}" for n in orders],
                [[k] + ["" if v[n] is None else num(v[n]) for n in orders] for k, v in b["class_model_counts"].items()]), ""]
    fp = fingerprints()
    if fp:
        L += ["OEIS lookups of the order-1..6 counts, searching the terms together with \"quasigroup\", \"latin\" or \"loop\" "
              "(pinned in `data/controls/oeis_fingerprints.tsv`; six matching terms are a lead, not a proof):", ""]
        L += [table(["counts n=1..6", "classes", "OEIS", "entry", "retrieved"], fp), ""]
    return L


def residual_json() -> dict | None:
    p = DER / "residual.json"
    return json.loads(p.read_text()) if p.exists() else None


def residual_section(n_unref: int, n_var: int, n_cls: int, r6: dict) -> list[str]:
    rj = residual_json()
    L = ["## Beyond the floor: smallest witnesses for the residual (Mace4; superseded by section 8)", ""]
    if rj is None or rj.get("status") != "ran" and "summary" not in rj:
        return L + [f"Not run ({(rj or {}).get('status', 'no data/derived/residual.json')}).", ""]
    s = rj["summary"]
    L += [
        f"Trust level differs from the rest of the report. For each of the {n_unref} residual pairs, {s['mace4']} searched "
        f"quasigroups satisfying the hypothesis and violating the goal at sizes {s['search']['start_size']}..{s['search']['end_size']} "
        f"in increasing order (time limit {s['search']['max_seconds']} s per pair). Orders ≤ 6 are excluded exhaustively by the floor. "
        "A reported model is therefore a witness of least order, provided Mace4's search at each smaller size is complete. "
        "Every model was re-evaluated with this repository's engine.",
        "",
        table(["check", "result"], [
            ["pairs searched", s["pairs"]],
            ["pairs with a witness found", s["witnessed"]],
            ["every witness satisfies the hypothesis and violates the goal (our engine)", s["all_verified"]],
            ["every witness signature is one of the varieties", s["all_signatures_are_varieties"]],
            ["every smaller size was searched to completion", s["all_minimal"]],
        ]),
        "",
        table(["least witness order", "class pairs"], [[o, c] for o, c in sorted(s["order_histogram"].items(), key=lambda kv: int(kv[0]))]),
        "",
        f"Largest order needed: {s['max_witness_order']}. Adding these {s['witnessed']} witnesses to the order-6 floor gives "
        f"{s['distinct_new_signatures']} new signatures, {s['with_floor_class_blocks']} blocks of the {n_cls} classes (from {r6['law_blocks']}) "
        f"and {s['with_floor_varieties_realised']} of {n_var} varieties realised (from {r6['varieties_realized']}); these are lower "
        "bounds for the full floor at that order.",
        "",
    ]
    groups: dict[tuple, list[int]] = {}
    for r in rj["rows"]:
        groups.setdefault((r["a"], r["order"]), []).append(r["b"])
    L += [
        f"- Sch-{a} ↛ " + ", ".join(f"Sch-{b}" for b in sorted(bs)) + f": least witness order {o if o is not None else 'not found'}"
        for (a, o), bs in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1] or 0))
    ]
    L += ["", "Witness tables: `data/derived/residual.json`.", ""]
    return L


def report(res: dict, g1rows: list[dict]) -> str:
    c = res["lefloch_consistency"]
    ps = res["pair_space"]
    rows = {r["order"]: r for r in res["per_order"]}
    iso_cum, acc = {}, 0
    for n in ORDERS:
        acc += rows[n]["iso_classes_at_order"]
        iso_cum[n] = acc
    r4, r6 = rows[4], rows[6]
    n_cls, n_var = c["n_classes"], c["n_long_classes"]
    cov = res["cover"]
    para = res["parastrophe"]
    fig = figure(res)
    m = machine()
    order2_sig = next(s for s in res["signatures"] if s["iso_classes_by_order"]["2"] > 0)

    L = [GEN, "", "# quadratula: the refutation floor of Schröder's 990 quasigroup laws", ""]
    L += [f"Ground truth: {CITE}. This report measures a quantity Le Floch's data makes computable; "
          "it does not revise his result, which is complete.", ""]

    L += ["## Headline", ""]
    L += [
        f"Le Floch's data has two levels that are easy to conflate: the {num(c['n_laws'])} laws fall into "
        f"**{n_cls} equivalence classes**, and conjunctions of laws define **{n_var} varieties** "
        f"(logically closed subsets, including the empty and the full set). Both are measured below.",
        "",
        f"**Quasigroups of order at most 4** ({num(iso_cum[4])} isomorphism classes in total) witness "
        f"**{pct(r4['class_saturation'])}** of the {num(ps['class_non_implications'])} non-implications between classes "
        f"({pct(r4['law_saturation'])} of the {num(ps['law_non_implications'])} non-implications between laws), "
        f"cut the {n_cls} classes into **{r4['law_blocks']} blocks** ({r4['classes_separated']} classes separated from all "
        f"others), and realise "
        f"**{r4['varieties_realized']} of the {n_var} varieties** as intersections of their signatures.",
        "",
        f"The {rows[3]['iso_classes_at_order']} quasigroups of order 3 alone witness {pct(rows[3]['law_saturation'])} of law "
        f"non-implications; the {rows[4]['iso_classes_at_order']} of order 4 add {pct(rows[4]['law_saturation'] - rows[3]['law_saturation'])}. "
        f"Up to law equivalence and the six parastrophes, the {num(ps['ordered_law_pairs_offdiagonal'])} ordered law pairs "
        f"shrink to {num(para['class_pair_orbits'])} orbits of class pairs, a "
        f"{ps['ordered_law_pairs_offdiagonal'] / para['class_pair_orbits']:.0f}× collapse; "
        f"{num(para['class_non_implication_orbits'])} of those orbits are non-implications.",
        "",
        f"**Order at most 6** ({num(iso_cum[6])} isomorphism classes) brings this to {pct(r6['class_saturation'])} of class "
        f"non-implications, {pct(r6['law_saturation'])} of law non-implications, {r6['law_blocks']} blocks "
        f"({r6['classes_separated']} of {n_cls} classes separated) and "
        f"{r6['varieties_realized']} of {n_var} varieties.",
        "",
        f"**The floor does not finish the job.** At order 6, {r6['class_unrefuted_non_implication']} class-level "
        f"non-implications ({num(r6['law_unrefuted_non_implication'])} law pairs) still have no witness, "
        f"{len(r6['merged_class_groups'])} groups of classes are still merged, and "
        f"{n_var - r6['varieties_realized']} varieties are not realised. Because the floor is exhaustive, any finite witness for "
        "these has order at least 7. The last two orders add little: order 5 adds "
        f"{rows[5]['class_pairs_new']} class pairs and order 6 adds {rows[6]['class_pairs_new']}, against "
        f"{rows[4]['class_pairs_new']} for order 4.",
        "",
        f"No quasigroup of order ≤ 6 refutes any implication Le Floch proves, and every one of the "
        f"{rows[6]['distinct_signatures_cumulative']} distinct signatures is one of his {n_var} closed sets (see [CONTROLS.md](CONTROLS.md)).",
        "",
        f"A cover of **{cov['ilp_optimum']} quasigroups** (proven optimal by ILP; greedy needs {cov['greedy_size']}) witnesses every "
        f"non-implication the floor witnesses. Their tables are printed in section 4.",
        "",
    ]
    if beyond_json() or residual_json():
        L += ["The sections after the divider go past this question, to orders 7–9; they are kept separate from the "
              "measurement above.", ""]

    L += ["## Definitions and denominators", ""]
    L += [
        "- A quasigroup of order n is an n×n Latin square. `a // b` is the `c` with `c * a = b` and `a \\\\ b` is the `c` "
        "with `b * c = a`: Le Floch's conjugate divisions (CONTROLS.md, step 0).",
        "- `sig(Q)` is the set of the 990 laws Q satisfies. Q witnesses `i ↛ j` iff `i ∈ sig(Q)` and `j ∉ sig(Q)`.",
        "- The floor at order k is all quasigroups of order ≤ k up to isomorphism.",
        f"- Law-level denominator: {num(ps['ordered_law_pairs_offdiagonal'])} ordered pairs of distinct laws, of which "
        f"{num(ps['law_implications_offdiagonal'])} are implications and {num(ps['law_non_implications'])} are non-implications.",
        f"- Class-level denominator: {num(ps['ordered_class_pairs_offdiagonal'])} ordered pairs of distinct classes, "
        f"{num(ps['class_implications_offdiagonal'])} implications, {num(ps['class_non_implications'])} non-implications.",
        f"- A variety is realised at order k if it equals the intersection of some set of signatures of the floor "
        f"(the empty intersection is the full set). Denominator: {n_var}.",
        "",
    ]

    L += ["## 1. Trivial-only laws", ""]
    L += [
        f"Laws satisfied by no quasigroup of order 2..k: "
        + ", ".join(f"k={n}: {rows[n]['trivial_only_laws']}" for n in ORDERS if n >= 2)
        + f". The single quasigroup of order 2 already satisfies {order2_sig['laws_satisfied']} of the "
        f"{num(c['n_laws'])} laws, so no law forces triviality and no pair is made vacuous "
        f"({rows[6]['trivial_only_vacuous_pairs']} vacuous pairs). It also witnesses nothing: orders 1 and 2 contribute "
        f"{rows[2]['class_refuted_non_implication']} witnessed pairs.",
        "",
    ]

    L += ["## 2. Saturation curve", ""]
    L += [f"![saturation]({fig})", ""]
    L += [table(
        ["max order k", "iso classes ≤ k", f"law non-implications witnessed (of {num(ps['law_non_implications'])})", "share",
         f"class non-implications witnessed (of {num(ps['class_non_implications'])})", "share"],
        [[n, num(iso_cum[n]), num(rows[n]["law_refuted_non_implication"]), pct(rows[n]["law_saturation"]),
          num(rows[n]["class_refuted_non_implication"]), pct(rows[n]["class_saturation"])] for n in ORDERS],
    ), ""]

    L += ["## 3. Class separation and varieties (headline)", ""]
    L += [
        "Laws with identical signature columns over the floor form one block. Equivalent laws always share a column, "
        f"so blocks are unions of Le Floch's classes; the partition can only be coarser than the {n_cls} classes.",
        "",
        table(
            ["max order k", f"blocks (of {n_cls} classes)", f"classes separated from all others (of {n_cls})",
             "groups of merged classes", f"varieties realised (of {n_var})",
             "varieties that are a single signature", "classes split by the floor"],
            [[n, rows[n]["law_blocks"], rows[n]["classes_separated"], len(rows[n]["merged_class_groups"]), rows[n]["varieties_realized"],
              rows[n]["varieties_as_single_signature"], rows[n]["classes_split_by_floor"]] for n in ORDERS],
        ),
        "",
        "Classes still merged, by representative:",
        "",
    ]
    for n in (3, 4, 5, 6):
        groups = rows[n]["merged_class_groups"]
        L.append(f"- order ≤ {n}: " + ("; ".join("{" + sch(g) + "}" for g in groups) if groups else "none"))
    L += ["", f"Varieties not realised at order ≤ 6 ({len(r6['missing_varieties'])}), named by a smallest generating set of "
          "representatives in Le Floch's style:", "",
          ", ".join(f"Sch-{v}" for v in r6["missing_varieties"]) or "none", ""]

    L += ["## 4. Minimum cover", ""]
    L += [
        f"Universe: the {num(cov['universe_class_pairs'])} class-level non-implications witnessed at order ≤ 6 "
        f"({num(cov['universe_law_pairs'])} law pairs; a class pair is covered exactly when all its law pairs are). "
        f"Candidates: the {cov['candidates_distinct_signatures']} distinct signatures, one least table each. "
        "Solver: HiGHS through `highspy`.",
        "",
        table(["method", "size", "status"], [
            ["greedy (most new pairs; ties to smaller order, then smaller table)", cov["greedy_size"], "heuristic"],
            ["LP relaxation lower bound", f"{cov['lp_bound']:.4f}", cov["lp_status"]],
            ["ILP optimum", cov["ilp_optimum"], cov["ilp_status"]],
        ]),
        "",
        f"Greedy is {cov['greedy_size'] - cov['ilp_optimum']} above the optimum. Among optimal covers, the one below minimises the "
        f"sum of orders ({cov['order_weighted_total_order']}; {cov['order_weighted_status']}).",
        "",
        "Optimal cover size when only quasigroups of order ≤ k may be used, covering what order ≤ k witnesses:",
        "",
        table(["max order k", "class pairs to cover", "optimal cover size"],
              [[k, num(v["universe_class_pairs"]), v["optimal_cover_size"]] for k, v in
               sorted(cov["optimal_by_max_order"].items(), key=lambda kv: int(kv[0]))]),
        "",
    ]
    profile = {}
    for q in cov["optimal"]:
        profile[q["order"]] = profile.get(q["order"], 0) + 1
    L += ["Order profile of the optimal cover: " + ", ".join(f"order {k}: {v}" for k, v in sorted(profile.items())) + ".", ""]
    L += ["The covering quasigroups (rows of the `*` table on {0..n-1}; `variety` is the variety the signature defines):", ""]
    for i, q in enumerate(cov["optimal"], 1):
        L += [f"**C{i}**: order {q['order']}, satisfies {q['laws_satisfied']} laws, variety Sch-{q['variety']}, "
              f"covers {q['class_pairs_covered']} class pairs ({num(q['law_pairs_covered'])} law pairs)", "",
              "```", *q["table_rows"], "```", ""]
    L += ["Machine-readable: `data/cover/min_cover.tsv`.", ""]

    L += ["## 5. Distinct signatures per order", ""]
    L += [table(
        ["order n", "iso classes at order n", "distinct signatures at order n", "new at order n", "cumulative ≤ n",
         "S3-canonical at order n", "S3-canonical cumulative"],
        [[n, num(rows[n]["iso_classes_at_order"]), rows[n]["distinct_signatures_at_order"], rows[n]["new_signatures"],
          rows[n]["distinct_signatures_cumulative"], para["canonical_signatures"][str(n)]["at_order"],
          para["canonical_signatures"][str(n)]["cumulative"]] for n in ORDERS],
    ), "",
        f"Isomorphism classes grow by {num(rows[6]['iso_classes_at_order'] // max(1, rows[5]['iso_classes_at_order']))}× from order 5 to 6; "
        f"distinct behaviours grow from {rows[5]['distinct_signatures_cumulative']} to {rows[6]['distinct_signatures_cumulative']}. "
        "Behaviour space is bounded above by the number of varieties, since every signature is a closed set.", ""]

    L += ["## 6. Parastrophe collapse", ""]
    fl = para["fixed_laws_per_sigma"]
    L += [
        f"The six parastrophes act on the law list itself: each σ maps the {num(c['n_laws'])} laws bijectively onto the list "
        f"(CONTROLS.md, G4). Fixed laws per σ: " + ", ".join(f"{k}: {v}" for k, v in fl.items()) + ".",
        "",
        table(["object", "size", "orbits under S3", "collapse factor"], [
            ["laws", num(c["n_laws"]), para["law_orbits"], f"{c['n_laws'] / para['law_orbits']:.2f}"],
            ["ordered pairs of distinct laws", num(ps["ordered_law_pairs_offdiagonal"]), num(para["ordered_pair_orbits"]),
             f"{ps['ordered_law_pairs_offdiagonal'] / para['ordered_pair_orbits']:.2f}"],
            ["law non-implications", num(ps["law_non_implications"]), num(para["non_implication_orbits"]),
             f"{ps['law_non_implications'] / para['non_implication_orbits']:.2f}"],
            ["equivalence classes", n_cls, para["class_orbits"], f"{n_cls / para['class_orbits']:.2f}"],
            ["ordered pairs of distinct classes", num(ps["ordered_class_pairs_offdiagonal"]), num(para["class_pair_orbits"]),
             f"{ps['ordered_class_pairs_offdiagonal'] / para['class_pair_orbits']:.2f}"],
            ["class non-implications", num(ps["class_non_implications"]), num(para["class_non_implication_orbits"]),
             f"{ps['class_non_implications'] / para['class_non_implication_orbits']:.2f}"],
            ["law pairs → orbits of class pairs (equivalence and S3 combined)", num(ps["ordered_law_pairs_offdiagonal"]),
             num(para["class_pair_orbits"]), f"{ps['ordered_law_pairs_offdiagonal'] / para['class_pair_orbits']:.2f}"],
            ["varieties", n_var, para["variety_orbits"], f"{n_var / para['variety_orbits']:.2f}"],
        ]),
        "",
        f"The group has order {para['group_order']}, against 2 for the opposite-magma duality in the magma setting. "
        f"A count that ignores it inflates the law pair space by a factor of "
        f"{ps['ordered_law_pairs_offdiagonal'] / para['ordered_pair_orbits']:.2f}, where duality alone can give at most 2 for magmas.",
        "",
    ]

    L += ["## 7. Marginal value of each order", ""]
    L += [table(
        ["order n", "new law pairs witnessed", "new class pairs witnessed", "new varieties realised", "new signatures"],
        [[n, num(rows[n]["law_pairs_new"]), num(rows[n]["class_pairs_new"]), rows[n]["varieties_new"], rows[n]["new_signatures"]]
         for n in ORDERS],
    ), ""]

    L += ["## Tiny quasigroups", "",
          f"The analogue of the magma result's degenerate objects: one row per distinct signature among the quasigroups of "
          f"order ≤ 3 (the unique quasigroup of order 2 has the same signature as order 1), with the share of the "
          f"{num(ps['law_non_implications'])} law non-implications it witnesses alone.", ""]
    L += [table(["order", "table", "laws satisfied", "variety", "law pairs witnessed", "share"],
                [[q["order"], "`" + " / ".join(q["table_rows"]) + "`", q["laws_satisfied"], f"Sch-{q['variety']}",
                  num(q["law_pairs_covered"]), pct(q["law_share_of_non_implications"])] for q in res["tiny_quasigroups"]]), ""]

    unref = res["unrefuted_class_non_implications_at_order_6"]
    by_src: dict[int, list[int]] = {}
    for a, b in unref:
        by_src.setdefault(a, []).append(b)
    L += ["## Residual: class non-implications without a witness of order ≤ 6", "",
          f"{len(unref)} ordered class pairs `Sch-a ↛ Sch-b`, grouped by `a`:", ""]
    L += [f"- Sch-{a} ↛ " + ", ".join(f"Sch-{b}" for b in bs) for a, bs in sorted(by_src.items())]
    L += [""]
    if beyond_json() or residual_json():
        L += ["---", "", "# Extension beyond the original question", "",
              "Sections 1–7 answer the question this project set out to answer: what quasigroups of order ≤ 6 account for. "
              "What follows goes further.", ""]
        bj = beyond_json()
        if bj and bj["curve"] and bj["complete_upto"] > 6:
            last = bj["curve"][-1]
            agree = sum(1 for p in bj["least_pair_order"] if p["exhaustive_least_order"] == p["mace4_order"])
            L += [f"Exactly, up to order {bj['complete_upto']}: quasigroups of order ≤ {bj['complete_upto']} witness "
                  f"{pct(last['class_saturation'])} of class non-implications, separate {last['classes_separated']} of {n_cls} classes "
                  f"and realise {last['varieties_realised']} of {n_var} varieties (section 8). Where both exist, the least "
                  f"witness orders of the residual pairs agree with Mace4 ({agree} of {len(bj['least_pair_order'])}).", ""]
        L += residual_section(len(unref), n_var, n_cls, r6)
        L += beyond_section(res, n_cls, n_var)

    L += ["## Compute", ""]
    L += [table(["order", "enumerate (s)", "signatures (s)", "plain Latin count (s)", "threads"],
                [[r["order"], f"{r['enumerate_seconds']:.2f}", f"{r['signature_seconds']:.2f}", f"{r['latin_seconds']:.2f}", r["threads"]]
                 for r in g1rows]), ""]
    L += [f"Machine: {m['cpu']}, {m['logical_cores']} logical cores, {int(m['memory_bytes']) // 2**30} GiB; {m['rustc']}; {m['python']}.", ""]

    L += ["## Reproduce", "", "```bash", "make reproduce", "```", "",
          "Requires rustup (toolchain pinned by `rust-toolchain.toml`) and uv (Python and packages pinned by "
          "`.python-version`, `pyproject.toml`, `uv.lock`).", ""]
    L += ["## Credit", "", f"All implication, class and variety data: {CITE}. Enumeration and signature code adapts parts of "
          "[parsimagma](https://github.com/carlok/parsimagma) (Apache-2.0); see NOTICE.", ""]
    return "\n".join(L)


def controls(res: dict, g1rows: list[dict]) -> str:
    c = res["lefloch_consistency"]
    survey = [line.split("\t") for line in (DER / "laws_survey.tsv").read_text().splitlines()]
    g3 = gates.g3()
    g4rows = gates.g4()
    seq = gates.oeis()
    para_rows = (DER / "parastrophe_summary.tsv").read_text().splitlines()
    rows = res["per_order"]
    shapes = [s for s in survey if s[0] == "laws_with_ops_lhs_rhs"]
    max_side = max(max(int(s[1]), int(s[2])) for s in shapes)

    L = [GEN, "", "# Controls", "",
         "Every gate below reruns from `make reproduce`; the pass/fail assertions live in `tests/test_gates.py` "
         "(full-size runs) and `tests/gates.rs` plus unit tests in `src/` (fast versions).", ""]

    L += ["## Step 0: the data and its format", "",
          f"Pinned files and SHA-256 digests: `data/lefloch/PROVENANCE.txt`. Source: {CITE}.", "",
          "Survey of `quasigroup-equations.txt` by the Rust parser (`qg laws`):", "",
          table(["quantity", "value"], [[" ".join(s[:-1]), s[-1]] for s in survey]), "",
          "Findings:", "",
          "- The laws use three operations `*`, `//`, `\\\\`, all primitive in the language. Following Le Floch §2.1, "
          "`x // y = y / x` and `x \\\\ y = y \\ x` are conjugates of the right and left divisions. On a Latin square this means "
          "`a // b` is the `c` with `c * a = b`, and `a \\\\ b` is the `c` with `b * c = a`. A unit test checks all six "
          "quasigroup axioms (5) of the paper under this reading.",
          "- Every side is fully parenthesised with exactly two operations; the parser rejects unparenthesised chains, "
          "unknown symbols and multi-letter names, and printing reproduces every line of the file.",
          f"- Le Floch's files describe {c['n_classes']} equivalence classes of single laws and {c['n_long_classes']} equivalence "
          "classes of conjunctions (closed sets, or varieties); his abstract counts the latter. The report keeps the two apart.",
          "- The implication file lists implications between representatives. Checks on it:", ""]
    L += [table(["check", "result"], [[k, v] for k, v in c.items()]), ""]
    L += [f"- Law-level ground truth: `i ⇒ j` iff `j` lies in the closed set of `i`'s representative "
          "(`quasigroup_eq_to_long_class.json`), which the check `closure_matches_implication_file` ties to the implication file.", ""]

    L += ["## G1: enumeration counts", "",
          f"Reference sequences looked up on OEIS on 2026-09-13: {seq['all']['oeis']} ({seq['all']['name']}) and "
          f"{seq['latin_squares']['oeis']} ({seq['latin_squares']['name']}).", "",
          table(["order", "iso classes", seq["all"]["oeis"], "Σ n!/#Aut", "plain count", seq["latin_squares"]["oeis"], "pass"],
                [[r["order"], num(r["iso_classes"]), num(r["oeis_iso"]), num(r["orbit_sum"]), num(r["latin_count"]),
                  num(r["oeis_latin"]), r["ok"]] for r in g1rows]), "",
          "The enumerator prunes with two necessary conditions for a lexicographically least table (first cell ≤ 1; row 0 least "
          "among its conjugates by permutations fixing 0). `enumerate::tests::pruning_is_sound_at_order_4` compares the pruned "
          "enumeration against an unpruned canonicity filter over all Latin squares of order 4. The orbit-stabiliser sum "
          "checks the automorphism counts independently of the plain backtracking count.", ""]

    L += ["## G2: Le Floch's implications reproduced", "",
          "Confusion matrices over the cumulative floor. \"Refuted\" means some quasigroup of order ≤ k witnesses the pair. "
          "The cell *refuted ∧ implication* must be 0; *unrefuted ∧ non-implication* is a result, not a failure.", ""]
    L += [table(
        ["k", "law: refuted ∧ impl", "law: refuted ∧ non-impl", "law: unrefuted ∧ non-impl", "law: unrefuted ∧ impl",
         "class: refuted ∧ impl", "class: refuted ∧ non-impl", "class: unrefuted ∧ non-impl", "class: unrefuted ∧ impl"],
        [[r["order"], r["law_refuted_but_implication"], num(r["law_refuted_non_implication"]), num(r["law_unrefuted_non_implication"]),
          num(r["law_unrefuted_implication"]), r["class_refuted_but_implication"], num(r["class_refuted_non_implication"]),
          num(r["class_unrefuted_non_implication"]), num(r["class_unrefuted_implication"])] for r in rows],
    ), ""]
    L += ["Two stronger checks follow from Le Floch's closed-set list: a signature is always closed under consequence, so it "
          "must be one of the listed varieties, and so must any intersection of signatures.", "",
          table(["k", "distinct signatures", "not among the varieties", "floor-closed sets", "not among the varieties",
                 "classes split by the floor"],
                [[r["order"], r["distinct_signatures_cumulative"], r["signatures_not_among_long_classes"], r["closed_sets"],
                  r["closed_sets_not_long_classes"], r["classes_split_by_floor"]] for r in rows]), ""]

    L += ["## G3: independent control", "",
          "A control based on the Bol-Moufang varieties of Phillips and Vojtěchovský is not possible here: a Bol-Moufang "
          f"identity has four multiplications on each side, while every one of the {num(c['n_laws'])} Schröder laws has at "
          f"most {max_side} operations on each side (survey above). The control uses classical counts from OEIS, which come from other authors "
          "and other methods and exercise the same parser, evaluator and enumeration. Laws are written directly in the "
          "control, and where Le Floch names a Schröder equivalent, the count is also read from the stored signatures.", "",
          f"Associativity `x * (y * z) = (x * y) * z` is Sch-{g3['associativity_id']} in the list.", ""]
    cols = gates.CONTROL_COLUMNS
    L += [table(["order"] + [f"{col} ({seq[col]['oeis']})" for col in cols],
                [[n] + [f"{g3['table'][n][col]} / {seq[col]['values'][n]}" for col in cols] for n in ORDERS]), "",
          "Cells are computed / OEIS. Definitions used: groups = associative; abelian = associative and commutative; "
          "semisymmetric = `x = y * (x * y)`; totally symmetric = semisymmetric and commutative; idempotent = `x * x = x` "
          f"(OEIS {seq['idempotent']['oeis']} diagonal T(n,n)).", "",
          f"All {len(g3['rows'])} control cells match: {all(r['ok'] for r in g3['rows'])}.", "",
          table(["Schröder law (from signatures)", "direct law", "orders agreeing"],
                [[{"sch_assoc": f"Sch-{g3['associativity_id']} (is associativity)",
                   "sch1_commutative": "Sch-1 (Le Floch: equivalent to commutativity)",
                   "sch5_semisymmetric": "Sch-5 (Le Floch: equivalent to x = y * (x * y))"}[k],
                  v, sum(1 for t in g3["twins"] if t["schroeder"] == k and t["ok"])] for k, v in gates.SCHROEDER_TWINS.items()]),
          ""]

    L += ["## G4: parastrophe equivariance", "",
          "The operation translation is derived from the triple picture (`src/parastrophe.rs`): σ permutes the positions of "
          "`(x, y, x*y)`, and each operation of Q^σ is an operation of Q with arguments possibly swapped. Laws are rewritten "
          "by this translation and matched back to the list up to renaming and side swap.", "",
          "```", *para_rows, "```", "",
          table(["order", "labeled Latin squares", "bit checks (6 σ × 990 laws each)", "mismatches"],
                [[r["order"], num(r["labeled_squares"]), num(r["bit_checks"]), r["mismatches"]] for r in g4rows]), "",
          "Exhaustive over every labeled Latin square of order ≤ 5. As a further check, "
          "the set of distinct signatures at each order is closed under the action: "
          + ", ".join(f"order {k}: {v}" for k, v in res["parastrophe"]["signature_sets_closed_under_action"].items()) + ".", ""]

    L += ["## Routines changed, failed or discarded", "",
          "- No gate failed and no routine was changed to make a gate pass.",
          "- The whole of S3 maps the law list to itself, because the language has all three operations (G4); no subgroup "
          "restriction was needed.",
          "- `analysis/compute.py` first crashed while serialising results (mixed integer and string keys); fixed before any "
          "number was read.",
          "- Discarded: a first Mace4 pilot driven from a shell here-document. The shell collapsed `\\\\` to a single backslash, "
          "so the laws Mace4 read were not Schröder's, and one pilot \"witness\" was invalid. The pipeline in "
          "`analysis/residual.py` passes the law text to Mace4 without a shell, and re-checks every model with the Rust engine "
          "against the intended hypothesis and goal.", ""]
    bj = beyond_json()
    if bj:
        L += ["## G5: exhaustive search beyond order 6", "",
              "- `search::tests::agrees_with_enumeration_through_order_5`: with no laws the search returns exactly the "
              "enumerator's isomorphism classes, and with each of seven sample laws it returns exactly the enumerated "
              "classes satisfying that law, for every order ≤ 5.",
              "- `analysis/beyond.py` asserts that every model found satisfies its generators and that its signature is "
              "one of Le Floch's varieties.",
              "- Independent count at orders the floor does not reach: Sch-5 implies Sch-23, so the models of Sch-23 that "
              "satisfy Sch-5 are the semisymmetric quasigroups.", "",
              table(["order", "models of Sch-23", "of which satisfy Sch-5", "OEIS", "expected", "match"],
                    [[r["order"], num(r["sch23_models"]), num(r["satisfying_sch5"]), r["oeis"],
                      "" if r["expected"] is None else num(r["expected"]), r["ok"]] for r in bj["semisymmetric_control"]]),
              "",
              table(["generators", "order", "result", "search nodes", "seconds"],
                    [[f"Sch-({d['laws']})", d["order"], d.get("iso_models", d.get("status")), num(int(d["nodes"])) if "nodes" in d else "",
                      d.get("seconds", "")] for d in bj["runs"]]), ""]
    ic_path = DER / "independent_checks.json"
    if ic_path.exists():
        ic = json.loads(ic_path.read_text())
        L += ["## G6: independent re-checks", "",
              "`analysis/independent_checks.py` shares no code with the Rust engine or the analysis scripts: it has its "
              "own law parser and evaluator, reads Le Floch's raw files, and uses kissat for SAT.", ""]
        cov = ic.get("cover")
        if cov:
            rows = [["cover up to order 6", cov["cover_order6"]["members"], num(cov["cover_order6"]["covered_non_implications"]),
                     cov["cover_order6"]["covers_an_implication"], cov["cover_order6"]["signatures_not_closed_sets"],
                     cov["cover_order6"]["ok"]]]
            if "full_cover" in cov:
                fc = cov["full_cover"]
                rows.append(["full cover", fc["members"], num(fc["covered_non_implications"]), fc["covers_an_implication"],
                             fc["signatures_not_closed_sets"], fc["ok"]])
            L += [table(["cover", "tables", "class non-implications witnessed", "implications witnessed",
                         "signatures not among the closed sets", "pass"], rows), ""]
        mo = ic.get("models")
        if mo:
            L += [f"Stored models: for {mo['pairs']} residual class pairs, a witness of the claimed least order was "
                  f"found again in `data/beyond/`: {mo['all_found']}.", ""]
        sat = ic.get("sat")
        if sat and sat.get("status") == "ran":
            L += [f"SAT (kissat, time limit {num(sat['time_limit_seconds'])} s per query). The controls test the encoding "
                  "on a known fact: associativity without commutativity needs a non-abelian group, whose smallest order is 6. "
                  + sat["note"], "",
                  table(["kind", "order", "hypotheses", "violates", "expected", "result", "model re-checked", "seconds", "pass"],
                        [[r["kind"], r["order"], ", ".join(f"Sch-{h}" for h in r["hypotheses"]),
                          "" if r["goal_violated"] is None else f"Sch-{r['goal_violated']}", r["expected"], r["result"],
                          r.get("model_rechecked", ""), r["seconds"], r["ok"]] for r in sat["rows"]]), ""]
        elif sat:
            L += [f"SAT: {sat.get('status')}.", ""]
    rj = residual_json()
    if rj and "summary" in rj:
        s = rj["summary"]
        L += ["## Residual witnesses (Mace4, re-checked)", "",
              table(["check", "result"], [
                  ["pairs", s["pairs"]], ["witnessed", s["witnessed"]],
                  ["hypothesis satisfied and goal violated, by our engine", s["all_verified"]],
                  ["signature is one of Le Floch's varieties", s["all_signatures_are_varieties"]],
                  ["floor plus witnesses: closed sets outside the varieties", s["with_floor_closed_sets_not_varieties"]],
                  ["all smaller sizes searched to completion", s["all_minimal"]],
              ]), ""]
    return "\n".join(L)


def main() -> None:
    res = gates.results()
    g1rows = gates.g1()
    (ROOT / "REPORT.md").write_text(report(res, g1rows))
    (ROOT / "CONTROLS.md").write_text(controls(res, g1rows))
    print("wrote REPORT.md, CONTROLS.md, figures/saturation.png")


if __name__ == "__main__":
    main()
